/** Feature-toggle strings, kept out of lib/i18n.ts so this work does not
 *  collide in one long file - merged into the main dictionaries there the
 *  same way lib/strings/income.ts and lib/strings/fire.ts are.
 *
 *  Covers: the Settings "Features" section, the "this feature is off" card
 *  shown on a gated page reached directly by URL, and the always-on
 *  dashboard base summary (components/dashboard/BaseSummary.tsx) that needs
 *  no asset tracking. */
export const en: Record<string, string> = {
  "set.features.title": "Features",
  "set.features.subtitle":
    "Turn on the parts of the app that fit how you manage money. Everything starts off for a new wallet.",
  "set.features.portfolio.label": "Assets",
  "set.features.portfolio.desc":
    "Track what you own (savings, investments, gold, crypto) and how it changes over time.",
  "set.features.fire.label": "Retirement",
  "set.features.fire.desc":
    "See how far you are from financial independence and how much to save.",
  "set.features.fire.dependency": "Turning Retirement on also turns on Assets.",
  "set.features.tax.label": "Calculators",
  "set.features.tax.desc":
    "Calculators: employment vs B2B, what gross you need for a given net.",
  "set.features.insights.label": "Insights",
  "set.features.insights.desc":
    "Short written summaries and next steps, generated by an AI model from your own numbers.",

  "feat.off.title": "This feature is turned off",
  "feat.off.goSettings": "Go to Settings",
  "feat.off.positions":
    "Turn on Assets in Settings to track what you own and see it here.",
  "feat.off.fire":
    "Turn on Retirement in Settings to see how far you are from financial independence.",
  "feat.off.tax":
    "Turn on Calculators in Settings to use the employment vs B2B calculators.",
  "feat.off.insights":
    "Turn on Insights in Settings to get AI-written summaries and next steps.",

  "dash.base.income": "Income this month",
  "dash.base.incomeHint": "Net, from your income sources",
  "dash.base.spent": "Spent this month",
  "dash.base.upcoming": "Coming up",
};

export const pl: Record<string, string> = {
  "set.features.title": "Funkcje",
  "set.features.subtitle":
    "Włącz te części aplikacji, które pasują do sposobu, w jaki zarządzasz pieniędzmi. W nowym portfelu wszystko jest domyślnie wyłączone.",
  "set.features.portfolio.label": "Aktywa",
  "set.features.portfolio.desc":
    "Śledź to, co posiadasz (oszczędności, inwestycje, złoto, kryptowaluty) i jak to się zmienia w czasie.",
  "set.features.fire.label": "Emerytura",
  "set.features.fire.desc":
    "Sprawdź, jak daleko Ci do niezależności finansowej i ile trzeba oszczędzać.",
  "set.features.fire.dependency": "Włączenie Emerytury włącza też Aktywa.",
  "set.features.tax.label": "Kalkulatory",
  "set.features.tax.desc":
    "Kalkulatory: etat a B2B, jaki brutto potrzebny do danego netto.",
  "set.features.insights.label": "Insights",
  "set.features.insights.desc":
    "Krótkie podsumowania i kolejne kroki pisane przez model AI na podstawie Twoich własnych liczb.",

  "feat.off.title": "Ta funkcja jest wyłączona",
  "feat.off.goSettings": "Przejdź do ustawień",
  "feat.off.positions":
    "Włącz Aktywa w Ustawieniach, aby śledzić to, co posiadasz, i zobaczyć to tutaj.",
  "feat.off.fire":
    "Włącz Emeryturę w Ustawieniach, aby zobaczyć, jak daleko Ci do niezależności finansowej.",
  "feat.off.tax":
    "Włącz Kalkulatory w Ustawieniach, aby korzystać z kalkulatorów etat / B2B.",
  "feat.off.insights":
    "Włącz Insights w Ustawieniach, aby otrzymywać podsumowania i kolejne kroki pisane przez AI.",

  "dash.base.income": "Dochód w tym miesiącu",
  "dash.base.incomeHint": "Netto, z Twoich źródeł dochodu",
  "dash.base.spent": "Wydano w tym miesiącu",
  "dash.base.upcoming": "Nadchodzące",
};
