/** Income + tax strings, kept out of lib/i18n.ts so feature work does not
 *  collide in one 700-line file. Merged into the main dictionaries there.
 *
 *  A few keys here (mon.income, mon.tblIncome's sibling hints) deliberately
 *  reuse existing lib/i18n.ts keys to retarget copy on /monthly for the new
 *  "income from sources" section - the merge order in i18n.ts
 *  (`{...en, ...incomeStrings.en}`) makes this file win on any shared key.
 */
export const en: Record<string, string> = {
  // ---- /monthly: retargeted + new copy for the sources integration ----
  "mon.income": "Other income (not from sources)",
  "mon.fromSources": "Income from sources",
  "mon.fromSourcesTotal": "Total from sources",
  "mon.fromSourcesEmpty": "No source income this month.",

  // ---- /income: page ----
  "inc.title": "Income",
  "inc.subtitle":
    "Recurring income sources, this year's schedule, and what part of your account isn't really yours yet.",
  "inc.addSource": "+ Add source",
  "inc.empty": "No income sources yet — add your first one.",
  "inc.confirmDelete": 'Delete "{name}"?',
  "inc.kindUop": "UoP",
  "inc.kindB2b": "B2B",
  "inc.kindOther": "Other",
  "inc.thisYearGross": "This year, gross / revenue",
  "inc.thisYearNet": "This year, net",
  "inc.thisYearTaxes": "This year, taxes & contributions",
  "inc.effectiveRate": "Effective rate",
  "inc.since": "Since {date}",
  "inc.until": "Until {date}",

  // Source summary line (built from these fragments, joined by " · ")
  "inc.sum.gross": "{amount} gross",
  "inc.sum.ppk": "PPK {pct}%",
  "inc.sum.ppkOptedOut": "PPK opted out",
  "inc.sum.pit2": "PIT-2",
  "inc.sum.youngRelief": "under-26 relief",
  "inc.sum.creative": "{pct}% creative KUP",
  "inc.sum.b2bForm": "B2B {form}",
  "inc.sum.ryczaltRate": "ryczałt {rate}%",
  "inc.sum.sickness": "voluntary sickness",
  "inc.sum.billingMonthly": "{amount} invoice",
  "inc.sum.billingDaily": "{rate}/day × {units}",
  "inc.sum.billingHourly": "{rate}/hr × {units}",
  "inc.sum.otherNet": "{amount} net, no tax",

  // Kind-specific vocabulary shared with /tax
  "inc.form.kupStandard": "Standard",
  "inc.form.kupCommuting": "Commuting (higher)",
  "inc.form.taxFormSkala": "Skala (12/32%)",
  "inc.form.taxFormLiniowy": "Liniowy (19% flat)",
  "inc.form.taxFormRyczalt": "Ryczałt",
  "inc.form.zusStart": "Ulga na start (no social contributions)",
  "inc.form.zusPreferential": "Preferential base",
  "inc.form.zusMzp": "Mały ZUS Plus",
  "inc.form.zusFull": "Full ZUS",
  "inc.form.vatStandard": "Standard",
  "inc.form.vatExempt": "Exempt (zwolnienie podmiotowe)",
  "inc.form.vatReverseCharge": "Reverse charge",

  // Source form
  "inc.form.newTitle": "New income source",
  "inc.form.editTitle": "Edit income source",
  "inc.form.name": "Name",
  "inc.form.namePlaceholder": "e.g. Main job, Client X",
  "inc.form.kind": "Kind",
  "inc.form.startsOn": "Starts on",
  "inc.form.hasEnd": "This source ends on a date",
  "inc.form.endsOn": "Ends on",
  "inc.form.indefiniteHint": "Leave unticked and it runs indefinitely.",
  "inc.form.grossMonthly": "Gross monthly",
  "inc.form.kup": "Tax-deductible costs (KUP)",
  "inc.form.creativeShare": "Creative work share (50% KUP)",
  "inc.form.pit2": "PIT-2 on file (300 PLN/month reduction)",
  "inc.form.youngRelief": "Under-26 relief (ulga dla młodych)",
  "inc.form.ppkEmployee": "PPK — employee %",
  "inc.form.ppkEmployer": "PPK — employer %",
  "inc.form.ppkOptOutHint":
    "0% opts out of PPK — you also forfeit the employer's 1.5% match and the state's one-off and annual payments.",
  "inc.form.billing": "Billing",
  "inc.form.billingMonthly": "Monthly invoice",
  "inc.form.billingDaily": "Daily rate",
  "inc.form.billingHourly": "Hourly rate",
  "inc.form.invoiceMonthly": "Invoice amount (monthly)",
  "inc.form.rate": "Rate",
  "inc.form.unitsPerMonth": "Units per month",
  "inc.form.useCalendar": "From the working-time calendar",
  "inc.form.calendarHint": "{days} days / {hours} h in {month}",
  "inc.form.costsMonthly": "Business costs (monthly)",
  "inc.form.taxForm": "Tax form",
  "inc.form.ryczaltRate": "Ryczałt rate",
  "inc.form.ryczaltHealthTier": "Health contribution tier",
  "inc.form.ryczaltHealthTierAuto": "Automatic (from this year's revenue)",
  "inc.form.ryczaltHealthTierOption": "Tier {tier} — {amount}/month ({range})",
  "inc.form.ryczaltHealthTierRangeTier1": "revenue up to {max}",
  "inc.form.ryczaltHealthTierRangeTier2": "revenue {min}–{max}",
  "inc.form.ryczaltHealthTierRangeTier3": "revenue above {min}",
  "inc.form.ryczaltHealthTierHint":
    "Most people pay the tier of last year's revenue; the difference is settled in the annual return.",
  "inc.form.zusStage": "ZUS stage",
  "inc.form.customBase": "Monthly ZUS base",
  "inc.form.customBaseHint": "Must be between {min} and {max} for {year}.",
  "inc.form.sickness": "Voluntary sickness insurance (chorobowe)",
  "inc.form.vat": "VAT",
  "inc.form.vatRate": "VAT rate",
  "inc.form.netMonthly": "Net monthly",
  "inc.form.otherHint":
    "No tax is calculated for this source — it's already net (rental, 800+, and similar).",
  "inc.form.addButton": "Add source",
  "inc.form.saveChanges": "Save changes",
  "inc.form.amountPositive": "Enter an amount of zero or more.",
  "inc.form.endAfterStart": "The end date must be on or after the start date.",

  // Year schedule
  "inc.schedule.title": "Year schedule",
  "inc.schedule.source": "Source",
  "inc.schedule.year": "Year",
  "inc.schedule.selectSource": "Select a source to see its year schedule.",
  "inc.schedule.month": "Month",
  "inc.schedule.amount": "Gross / revenue",
  "inc.schedule.unitsDays": "Days",
  "inc.schedule.unitsHours": "Hours",
  "inc.schedule.unitsCalendar": "calendar",
  "inc.schedule.unitsFixed": "fixed",
  "inc.schedule.unitsEntry": "entered",
  "inc.schedule.social": "ZUS social",
  "inc.schedule.health": "Health",
  "inc.schedule.pit": "PIT advance",
  "inc.schedule.ppkOrVat": "PPK / VAT due",
  "inc.schedule.net": "Net / take-home",
  "inc.schedule.overridden": "overridden",
  "inc.schedule.inactive": "not active",
  "inc.schedule.clickToEdit": "Click a month to edit its entry, or clear one already set.",
  "inc.schedule.summaryTitle": "Year summary",
  "inc.schedule.totalGross": "Total gross / revenue",
  "inc.schedule.totalNet": "Total net",
  "inc.schedule.totalTaxes": "Total taxes & contributions",
  "inc.schedule.settlement": "April settlement",
  "inc.schedule.settlementPay": "To pay: {amount}",
  "inc.schedule.settlementRefund": "Refund: {amount}",
  "inc.schedule.employerCost": "Employer cost (annual)",
  "inc.schedule.setAside": "Total set aside (B2B)",
  "inc.schedule.healthSettlementTitle": "Health settlement in the annual return",
  "inc.schedule.healthSettlementPay": "To pay: {amount} (revenue implies tier {tier})",
  "inc.schedule.healthSettlementRefund": "Overpaid: {amount} (revenue implies tier {tier})",
  "inc.schedule.otherNote": "No tax maths applies to this source.",

  // Month entry modal
  "inc.entry.title": "{month} entry",
  "inc.entry.amount": "Amount",
  "inc.entry.costs": "Costs",
  "inc.entry.revenuePreview": "Revenue: {amount}",
  "inc.entry.overrideNet": "Override net (actual, from a payslip or statement)",
  "inc.entry.overrideNetHint": "Wins over the estimate above when set.",
  "inc.entry.clear": "Clear entry",
  "inc.entry.confirmClear": "Clear the entry for {month}?",
  "inc.entry.useCalendar": "Use calendar",
  "inc.entry.confirmUseCalendar": "Switch {month} back to the working-time calendar?",

  // Tax envelope
  "inc.envelope.title": "Money on your account that is not yours",
  "inc.envelope.explain":
    "VAT and PIT/ZUS advances are collected by you on the state's behalf until their due date — this is what to keep untouched.",
  "inc.envelope.zus": "ZUS + health",
  "inc.envelope.pit": "PIT advance",
  "inc.envelope.vat": "VAT",
  "inc.envelope.due": "due {date}",
  "inc.envelope.windowPassed": "window passed",
  "inc.envelope.empty": "Nothing outstanding for the last two months.",
  "inc.envelope.total": "Total outstanding",

  // Year overview chart
  "inc.chart.title": "Year overview",
  "inc.chart.subtitle": "Net take-home vs. what's withheld, per month.",
  "inc.chart.net": "Net",
  "inc.chart.social": "ZUS social",
  "inc.chart.health": "Health",
  "inc.chart.pit": "PIT advance",
  "inc.chart.ppk": "PPK",
  "inc.chart.empty": "Add a source with some months of income to see this chart.",

  // Show-the-working
  "inc.working.show": "Show the working",
  "inc.working.hide": "Hide the working",
  "inc.field.gross": "Gross",
  "inc.field.pension": "Pension (emerytalne)",
  "inc.field.disability": "Disability (rentowe)",
  "inc.field.sickness": "Sickness (chorobowe)",
  "inc.field.employee_social": "ZUS social (employee)",
  "inc.field.health": "Health contribution (składka zdrowotna)",
  "inc.field.kup": "KUP (tax-deductible costs)",
  "inc.field.pit_base": "PIT base",
  "inc.field.pit_advance": "PIT advance (zaliczka)",
  "inc.field.ppk_employee": "PPK — employee",
  "inc.field.ppk_employer": "PPK — employer",
  "inc.field.net": "Net",
  "inc.field.employer_pension": "Employer pension",
  "inc.field.employer_disability": "Employer disability",
  "inc.field.employer_accident": "Employer accident",
  "inc.field.employer_fp": "Employer Labour Fund (FP)",
  "inc.field.employer_fgsp": "Employer FGŚP",
  "inc.field.employer_cost": "Total employer cost",
  "inc.field.revenue": "Revenue",
  "inc.field.costs": "Costs",
  "inc.field.invoice_gross": "Invoice gross (incl. VAT)",
  "inc.field.vat_output": "VAT output",
  "inc.field.vat_input": "VAT input",
  "inc.field.vat_due": "VAT due",
  "inc.field.social_total": "ZUS social (total)",
  "inc.field.income": "Taxable income",
  "inc.field.take_home": "Take-home",
  "inc.field.set_aside": "Set aside for taxes",
  "inc.field.base": "ZUS base",
  "inc.field.accident": "Accident",
  "inc.field.fp": "Labour Fund (FP)",
  "inc.field.total": "Total",

  // ---- /tax: page ----
  "tax.title": "Tax calculators",
  "tax.subtitle":
    "Compare umowa o pracę and B2B, work backwards from a target net, and see this year's Polish tax parameters. Nothing here is saved.",
  "tax.disclaimer":
    "Estimates for planning and learning, based on {year} rules. Not tax advice — confirm with your accountant or payslip.",
  "tax.calculate": "Calculate",
  "tax.calculating": "Calculating…",
  "tax.year": "Year",

  "tax.cmp.title": "UoP ↔ B2B comparator",
  "tax.cmp.subtitle":
    "What a given UoP gross and a given B2B revenue actually leave you, side by side.",
  "tax.cmp.uopGross": "UoP gross monthly",
  "tax.cmp.b2bRevenue": "B2B revenue monthly",
  "tax.cmp.b2bCosts": "B2B costs monthly",
  "tax.cmp.paidLeave": "Paid leave days",
  "tax.cmp.workingDays": "Working days",
  "tax.cmp.billedPerDay": "B2B billed per day worked (unpaid leave reduces revenue)",
  "tax.cmp.uopAnnualNet": "UoP annual net",
  "tax.cmp.uopEmployerCost": "UoP employer cost (annual)",
  "tax.cmp.b2bAnnualTakeHome": "B2B annual take-home",
  "tax.cmp.difference": "Difference (B2B − UoP)",
  "tax.cmp.equivalentRevenue": "B2B equivalent revenue (monthly)",
  "tax.cmp.equivalentHint": "What B2B would need to bill to match UoP's net.",
  "tax.cmp.pensionGap": "Pension gap (annual)",
  "tax.cmp.pensionGapNote":
    "This much less lands on your ZUS pension account every year on B2B — part of the higher net is borrowed from your future pension.",

  "tax.rev.title": "Reverse calculator",
  "tax.rev.subtitle": "Target net per month → what you'd need to earn under each form.",
  "tax.rev.targetNet": "Target net per month",
  "tax.rev.costsMonthly": "B2B costs monthly",
  "tax.rev.form": "Form",
  "tax.rev.formUop": "UoP",
  "tax.rev.formSkala": "B2B — skala",
  "tax.rev.formLiniowy": "B2B — liniowy",
  "tax.rev.formRyczalt": "B2B — ryczałt",
  "tax.rev.grossOrRevenue": "Gross / revenue needed",
  "tax.rev.achievedNet": "Achieved net",
  "tax.rev.effectiveRate": "Effective rate",

  "tax.hint.title": "Best form for this income",
  "tax.hint.best": "{form} gives the highest take-home at this income level.",
  "tax.hint.deadline":
    "You can change your tax form by the 20th of the month after your first revenue in the year (usually 20 February).",

  "tax.params.title": "{year} parameters",
  "tax.params.subtitle":
    "Every rate and threshold this engine uses, with the source it was checked against.",
  "tax.params.minWage": "Minimum wage",
  "tax.params.avgWageForecast": "Forecast average wage",
  "tax.params.avgWageQ4": "Average wage, Q4 previous year",
  "tax.params.zusCap": "ZUS annual cap (30×)",
  "tax.params.jdgFullBase": "JDG full ZUS base",
  "tax.params.jdgPrefBase": "JDG preferential base",
  "tax.params.healthMinMonthly": "JDG health minimum (monthly)",
  "tax.params.linearHealthLimit": "Liniowy health deduction limit (annual)",
  "tax.params.ryczaltTiers": "Ryczałt health tiers (monthly)",
  "tax.params.vatExemptLimit": "VAT exemption limit",
  "tax.params.ikeLimit": "IKE limit",
  "tax.params.ikzeLimit": "IKZE limit (employee)",
  "tax.params.ikzeLimitJdg": "IKZE limit (JDG)",
  "tax.params.pitThreshold": "PIT threshold (32% above)",
  "tax.params.pitRates": "PIT rates",
  "tax.params.linearRate": "Liniowy rate",
  "tax.params.workingTime": "Working time (days / hours)",
  "tax.params.holidays": "Public holidays this year",
  "tax.params.verifiedOn": "Verified {date}",
  "tax.params.sources": "Sources",
};

export const pl: Record<string, string> = {
  // ---- /monthly ----
  "mon.income": "Inne dochody (spoza źródeł)",
  "mon.fromSources": "Dochód ze źródeł",
  "mon.fromSourcesTotal": "Suma ze źródeł",
  "mon.fromSourcesEmpty": "Brak dochodu ze źródeł w tym miesiącu.",

  // ---- /income ----
  "inc.title": "Dochody",
  "inc.subtitle":
    "Cykliczne źródła dochodu, harmonogram na ten rok i część konta, która jeszcze nie jest Twoja.",
  "inc.addSource": "+ Dodaj źródło",
  "inc.empty": "Brak źródeł dochodu — dodaj pierwsze.",
  "inc.confirmDelete": 'Usunąć „{name}”?',
  "inc.kindUop": "UoP",
  "inc.kindB2b": "B2B",
  "inc.kindOther": "Inne",
  "inc.thisYearGross": "W tym roku, brutto / przychód",
  "inc.thisYearNet": "W tym roku, netto",
  "inc.thisYearTaxes": "W tym roku, podatki i składki",
  "inc.effectiveRate": "Stopa efektywna",
  "inc.since": "Od {date}",
  "inc.until": "Do {date}",

  "inc.sum.gross": "{amount} brutto",
  "inc.sum.ppk": "PPK {pct}%",
  "inc.sum.ppkOptedOut": "PPK — rezygnacja",
  "inc.sum.pit2": "PIT-2",
  "inc.sum.youngRelief": "ulga dla młodych",
  "inc.sum.creative": "{pct}% 50% KUP",
  "inc.sum.b2bForm": "B2B {form}",
  "inc.sum.ryczaltRate": "ryczałt {rate}%",
  "inc.sum.sickness": "dobrowolne chorobowe",
  "inc.sum.billingMonthly": "{amount} faktura",
  "inc.sum.billingDaily": "{rate}/dzień × {units}",
  "inc.sum.billingHourly": "{rate}/godz × {units}",
  "inc.sum.otherNet": "{amount} netto, bez podatku",

  "inc.form.kupStandard": "Standardowe",
  "inc.form.kupCommuting": "Dojazdowe (wyższe)",
  "inc.form.taxFormSkala": "Skala (12/32%)",
  "inc.form.taxFormLiniowy": "Liniowy (19%)",
  "inc.form.taxFormRyczalt": "Ryczałt",
  "inc.form.zusStart": "Ulga na start (bez składek społecznych)",
  "inc.form.zusPreferential": "Podstawa preferencyjna",
  "inc.form.zusMzp": "Mały ZUS Plus",
  "inc.form.zusFull": "Pełny ZUS",
  "inc.form.vatStandard": "Standardowy",
  "inc.form.vatExempt": "Zwolnienie podmiotowe",
  "inc.form.vatReverseCharge": "Odwrotne obciążenie",

  "inc.form.newTitle": "Nowe źródło dochodu",
  "inc.form.editTitle": "Edytuj źródło dochodu",
  "inc.form.name": "Nazwa",
  "inc.form.namePlaceholder": "np. Praca etatowa, Klient X",
  "inc.form.kind": "Rodzaj",
  "inc.form.startsOn": "Od",
  "inc.form.hasEnd": "To źródło kończy się w określonym dniu",
  "inc.form.endsOn": "Do",
  "inc.form.indefiniteHint": "Nie zaznaczaj, jeśli trwa bezterminowo.",
  "inc.form.grossMonthly": "Brutto miesięcznie",
  "inc.form.kup": "Koszty uzyskania przychodu (KUP)",
  "inc.form.creativeShare": "Udział pracy twórczej (50% KUP)",
  "inc.form.pit2": "PIT-2 złożony (ulga 300 zł/mies.)",
  "inc.form.youngRelief": "Ulga dla młodych (do 26 lat)",
  "inc.form.ppkEmployee": "PPK — pracownik %",
  "inc.form.ppkEmployer": "PPK — pracodawca %",
  "inc.form.ppkOptOutHint":
    "0% oznacza rezygnację z PPK — tracisz też dopłatę pracodawcy (1,5%) oraz wpłaty państwa.",
  "inc.form.billing": "Rozliczenie",
  "inc.form.billingMonthly": "Faktura miesięczna",
  "inc.form.billingDaily": "Stawka dzienna",
  "inc.form.billingHourly": "Stawka godzinowa",
  "inc.form.invoiceMonthly": "Kwota faktury (miesięcznie)",
  "inc.form.rate": "Stawka",
  "inc.form.unitsPerMonth": "Jednostek miesięcznie",
  "inc.form.useCalendar": "Z kalendarza czasu pracy",
  "inc.form.calendarHint": "{days} dni / {hours} godz w {month}",
  "inc.form.costsMonthly": "Koszty działalności (miesięcznie)",
  "inc.form.taxForm": "Forma opodatkowania",
  "inc.form.ryczaltRate": "Stawka ryczałtu",
  "inc.form.ryczaltHealthTier": "Próg składki zdrowotnej",
  "inc.form.ryczaltHealthTierAuto": "Automatycznie (z tegorocznego przychodu)",
  "inc.form.ryczaltHealthTierOption": "Próg {tier} — {amount}/mies. ({range})",
  "inc.form.ryczaltHealthTierRangeTier1": "przychód do {max}",
  "inc.form.ryczaltHealthTierRangeTier2": "przychód {min}–{max}",
  "inc.form.ryczaltHealthTierRangeTier3": "przychód powyżej {min}",
  "inc.form.ryczaltHealthTierHint":
    "Większość osób płaci próg z zeszłorocznego przychodu — różnicę rozlicza się w zeznaniu rocznym.",
  "inc.form.zusStage": "Etap ZUS",
  "inc.form.customBase": "Miesięczna podstawa ZUS",
  "inc.form.customBaseHint": "Musi mieścić się między {min} a {max} dla {year} r.",
  "inc.form.sickness": "Dobrowolne ubezpieczenie chorobowe",
  "inc.form.vat": "VAT",
  "inc.form.vatRate": "Stawka VAT",
  "inc.form.netMonthly": "Netto miesięcznie",
  "inc.form.otherHint":
    "Dla tego źródła nie liczymy podatku — kwota jest już netto (najem, 800+ itp.).",
  "inc.form.addButton": "Dodaj źródło",
  "inc.form.saveChanges": "Zapisz zmiany",
  "inc.form.amountPositive": "Podaj kwotę zero lub większą.",
  "inc.form.endAfterStart":
    "Data zakończenia musi być taka sama lub późniejsza niż data rozpoczęcia.",

  "inc.schedule.title": "Harmonogram roczny",
  "inc.schedule.source": "Źródło",
  "inc.schedule.year": "Rok",
  "inc.schedule.selectSource": "Wybierz źródło, aby zobaczyć jego harmonogram roczny.",
  "inc.schedule.month": "Miesiąc",
  "inc.schedule.amount": "Brutto / przychód",
  "inc.schedule.unitsDays": "Dni",
  "inc.schedule.unitsHours": "Godziny",
  "inc.schedule.unitsCalendar": "kalendarz",
  "inc.schedule.unitsFixed": "stałe",
  "inc.schedule.unitsEntry": "wpisane",
  "inc.schedule.social": "ZUS społeczne",
  "inc.schedule.health": "Zdrowotna",
  "inc.schedule.pit": "Zaliczka PIT",
  "inc.schedule.ppkOrVat": "PPK / VAT do zapłaty",
  "inc.schedule.net": "Netto / do ręki",
  "inc.schedule.overridden": "nadpisane",
  "inc.schedule.inactive": "nieaktywne",
  "inc.schedule.clickToEdit":
    "Kliknij miesiąc, aby edytować jego wpis, albo wyczyścić już ustawiony.",
  "inc.schedule.summaryTitle": "Podsumowanie roku",
  "inc.schedule.totalGross": "Suma brutto / przychodu",
  "inc.schedule.totalNet": "Suma netto",
  "inc.schedule.totalTaxes": "Suma podatków i składek",
  "inc.schedule.settlement": "Rozliczenie kwietniowe",
  "inc.schedule.settlementPay": "Do zapłaty: {amount}",
  "inc.schedule.settlementRefund": "Zwrot: {amount}",
  "inc.schedule.employerCost": "Koszt pracodawcy (rocznie)",
  "inc.schedule.setAside": "Suma odłożona (B2B)",
  "inc.schedule.healthSettlementTitle": "Rozliczenie zdrowotnej w zeznaniu rocznym",
  "inc.schedule.healthSettlementPay": "Do zapłaty: {amount} (przychód wskazuje próg {tier})",
  "inc.schedule.healthSettlementRefund": "Nadpłata: {amount} (przychód wskazuje próg {tier})",
  "inc.schedule.otherNote": "Dla tego źródła nie stosuje się matematyki podatkowej.",

  "inc.entry.title": "Wpis za {month}",
  "inc.entry.amount": "Kwota",
  "inc.entry.costs": "Koszty",
  "inc.entry.revenuePreview": "Przychód: {amount}",
  "inc.entry.overrideNet": "Nadpisz netto (rzeczywiste, z paska lub wyciągu)",
  "inc.entry.overrideNetHint": "Gdy ustawione, wygrywa z szacunkiem powyżej.",
  "inc.entry.clear": "Wyczyść wpis",
  "inc.entry.confirmClear": "Wyczyścić wpis za {month}?",
  "inc.entry.useCalendar": "Użyj kalendarza",
  "inc.entry.confirmUseCalendar": "Przełączyć {month} z powrotem na kalendarz czasu pracy?",

  "inc.envelope.title": "Pieniądze na koncie, które nie są Twoje",
  "inc.envelope.explain":
    "VAT oraz zaliczki na PIT/ZUS pobierasz w imieniu państwa do dnia ich terminu — to jest to, czego nie ruszać.",
  "inc.envelope.zus": "ZUS + zdrowotna",
  "inc.envelope.pit": "Zaliczka PIT",
  "inc.envelope.vat": "VAT",
  "inc.envelope.due": "termin {date}",
  "inc.envelope.windowPassed": "termin minął",
  "inc.envelope.empty": "Brak zaległości za ostatnie dwa miesiące.",
  "inc.envelope.total": "Suma zaległości",

  "inc.chart.title": "Przegląd roku",
  "inc.chart.subtitle": "Netto do ręki vs. to, co pobrane, w każdym miesiącu.",
  "inc.chart.net": "Netto",
  "inc.chart.social": "ZUS społeczne",
  "inc.chart.health": "Zdrowotna",
  "inc.chart.pit": "Zaliczka PIT",
  "inc.chart.ppk": "PPK",
  "inc.chart.empty": "Dodaj źródło z choć kilkoma miesiącami dochodu, aby zobaczyć wykres.",

  "inc.working.show": "Pokaż wyliczenie",
  "inc.working.hide": "Ukryj wyliczenie",
  "inc.field.gross": "Brutto",
  "inc.field.pension": "Emerytalne",
  "inc.field.disability": "Rentowe",
  "inc.field.sickness": "Chorobowe",
  "inc.field.employee_social": "ZUS społeczne (pracownik)",
  "inc.field.health": "Składka zdrowotna",
  "inc.field.kup": "KUP (koszty uzyskania przychodu)",
  "inc.field.pit_base": "Podstawa PIT",
  "inc.field.pit_advance": "Zaliczka na PIT",
  "inc.field.ppk_employee": "PPK — pracownik",
  "inc.field.ppk_employer": "PPK — pracodawca",
  "inc.field.net": "Netto",
  "inc.field.employer_pension": "Emerytalne (pracodawca)",
  "inc.field.employer_disability": "Rentowe (pracodawca)",
  "inc.field.employer_accident": "Wypadkowe (pracodawca)",
  "inc.field.employer_fp": "Fundusz Pracy (pracodawca)",
  "inc.field.employer_fgsp": "FGŚP (pracodawca)",
  "inc.field.employer_cost": "Całkowity koszt pracodawcy",
  "inc.field.revenue": "Przychód",
  "inc.field.costs": "Koszty",
  "inc.field.invoice_gross": "Kwota brutto faktury (z VAT)",
  "inc.field.vat_output": "VAT należny",
  "inc.field.vat_input": "VAT naliczony",
  "inc.field.vat_due": "VAT do zapłaty",
  "inc.field.social_total": "ZUS społeczne (razem)",
  "inc.field.income": "Dochód podatkowy",
  "inc.field.take_home": "Do ręki",
  "inc.field.set_aside": "Odłożone na podatki",
  "inc.field.base": "Podstawa ZUS",
  "inc.field.accident": "Wypadkowe",
  "inc.field.fp": "Fundusz Pracy (FP)",
  "inc.field.total": "Razem",

  // ---- /tax ----
  "tax.title": "Kalkulatory podatkowe",
  "tax.subtitle":
    "Porównaj umowę o pracę i B2B, policz wstecz od docelowego netto i zobacz tegoroczne parametry podatkowe. Nic tu się nie zapisuje.",
  "tax.disclaimer":
    "Szacunki do planowania i nauki, oparte na przepisach z {year} roku. To nie porada podatkowa — potwierdź z księgową/księgowym lub na pasku wypłaty.",
  "tax.calculate": "Oblicz",
  "tax.calculating": "Liczenie…",
  "tax.year": "Rok",

  "tax.cmp.title": "Porównanie UoP ↔ B2B",
  "tax.cmp.subtitle":
    "Ile realnie zostaje przy danym brutto na UoP i danym przychodzie na B2B, obok siebie.",
  "tax.cmp.uopGross": "UoP brutto miesięcznie",
  "tax.cmp.b2bRevenue": "B2B przychód miesięcznie",
  "tax.cmp.b2bCosts": "B2B koszty miesięcznie",
  "tax.cmp.paidLeave": "Dni urlopu płatnego",
  "tax.cmp.workingDays": "Dni robocze",
  "tax.cmp.billedPerDay": "B2B rozliczane za przepracowany dzień (urlop obniża przychód)",
  "tax.cmp.uopAnnualNet": "UoP netto rocznie",
  "tax.cmp.uopEmployerCost": "UoP koszt pracodawcy (rocznie)",
  "tax.cmp.b2bAnnualTakeHome": "B2B do ręki rocznie",
  "tax.cmp.difference": "Różnica (B2B − UoP)",
  "tax.cmp.equivalentRevenue": "B2B przychód równoważny (miesięcznie)",
  "tax.cmp.equivalentHint": "Ile B2B musiałoby fakturować, aby dorównać netto z UoP.",
  "tax.cmp.pensionGap": "Luka emerytalna (rocznie)",
  "tax.cmp.pensionGapNote":
    "Tyle mniej trafia na Twoje konto emerytalne ZUS co roku na B2B — część wyższego netto to pożyczka od przyszłej emerytury.",

  "tax.rev.title": "Kalkulator wsteczny",
  "tax.rev.subtitle": "Docelowe netto miesięcznie → ile trzeba zarobić w każdej formie.",
  "tax.rev.targetNet": "Docelowe netto miesięcznie",
  "tax.rev.costsMonthly": "B2B koszty miesięcznie",
  "tax.rev.form": "Forma",
  "tax.rev.formUop": "UoP",
  "tax.rev.formSkala": "B2B — skala",
  "tax.rev.formLiniowy": "B2B — liniowy",
  "tax.rev.formRyczalt": "B2B — ryczałt",
  "tax.rev.grossOrRevenue": "Potrzebne brutto / przychód",
  "tax.rev.achievedNet": "Osiągnięte netto",
  "tax.rev.effectiveRate": "Stopa efektywna",

  "tax.hint.title": "Najlepsza forma dla tego dochodu",
  "tax.hint.best": "{form} daje najwyższe netto przy tym poziomie dochodu.",
  "tax.hint.deadline":
    "Formę opodatkowania możesz zmienić do 20. dnia miesiąca następującego po pierwszym przychodzie w roku (zwykle 20 lutego).",

  "tax.params.title": "Parametry {year}",
  "tax.params.subtitle":
    "Każda stawka i próg używane przez ten silnik, ze źródłem, wobec którego zostały sprawdzone.",
  "tax.params.minWage": "Płaca minimalna",
  "tax.params.avgWageForecast": "Prognozowane przeciętne wynagrodzenie",
  "tax.params.avgWageQ4": "Przeciętne wynagrodzenie, IV kwartał poprz. roku",
  "tax.params.zusCap": "Roczny limit podstawy ZUS (30×)",
  "tax.params.jdgFullBase": "Pełna podstawa ZUS JDG",
  "tax.params.jdgPrefBase": "Podstawa preferencyjna JDG",
  "tax.params.healthMinMonthly": "Minimalna składka zdrowotna JDG (miesięcznie)",
  "tax.params.linearHealthLimit": "Limit odliczenia zdrowotnej dla liniowego (rocznie)",
  "tax.params.ryczaltTiers": "Progi zdrowotne ryczałtu (miesięcznie)",
  "tax.params.vatExemptLimit": "Limit zwolnienia z VAT",
  "tax.params.ikeLimit": "Limit IKE",
  "tax.params.ikzeLimit": "Limit IKZE (etat)",
  "tax.params.ikzeLimitJdg": "Limit IKZE (JDG)",
  "tax.params.pitThreshold": "Próg PIT (powyżej 32%)",
  "tax.params.pitRates": "Stawki PIT",
  "tax.params.linearRate": "Stawka liniowa",
  "tax.params.workingTime": "Wymiar czasu pracy (dni / godziny)",
  "tax.params.holidays": "Dni ustawowo wolne w tym roku",
  "tax.params.verifiedOn": "Zweryfikowano {date}",
  "tax.params.sources": "Źródła",
};
